# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  # vmImage: 'ubuntu-latest'
  vmImage: 'macOS 10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'Run lint'

- script: npm run test
  displayName: 'Run unit tests'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleDeveloperCertificate.p12
    certPwd: $(P12password)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AppleProvisioningProfile.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'
